# примеры API-запросов
@baseURL = http://127.0.0.1:8000/api
# получение объявлений
GET {{baseURL}}/advertisements/
Content-Type: application/json

###
# создание объявления
POST {{baseURL}}/advertisements/
Content-Type: application/json
Authorization: Token b1b782adf8594a584fa260d3e1c50802fd798b39

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseURL}}/advertisements/1/
Content-Type: application/json
Authorization: Token b1b782adf8594a584fa260d3e1c50802fd798b39

{
  "status": "CLOSED"
}

###

# фильтрация по создателю
GET {{baseURL}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseURL}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json

###

DELETE {{baseURL}}/advertisements/1/
Content-Type: application/json