# примеры API-запросов
@baseURL = http://127.0.0.1:8000/api
# получение объявлений
GET {{baseURL}}/advertisements/
Content-Type: application/json

###
# создание объявления
POST {{baseURL}}/advertisements/
Content-Type: application/json
Authorization: Token ba20df7358922147448330d94c335300e301f9d7

{
  "title": "стол IKEA",
  "description": "деревянный"
}

###

# попытка поменять объявление
PATCH {{baseURL}}/advertisements/1/
Content-Type: application/json
Authorization: Token ba20df7358922147448330d94c335300e301f9d7

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseURL}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseURL}}/advertisements/?created_at_before=2021-04-11
Content-Type: application/json

###

DELETE {{baseURL}}/advertisements/3/
Content-Type: application/json